package com.karan.intellijplatformplugin.generator;

import com.intellij.ide.highlighter.JavaFileType;
import com.intellij.openapi.project.Project;
import com.intellij.psi.*;
import com.karan.intellijplatformplugin.model.ClassMeta;
import com.karan.intellijplatformplugin.util.FileExistsUtil;
import com.karan.intellijplatformplugin.util.PsiDirectoryUtil;

import java.util.List;

/**
 * Generates the {@code BaseAuditEntity} mapped superclass with JPA auditing support.
 *
 * <p>Multi-entity changes:
 * <ul>
 *   <li>Accepts {@code List<ClassMeta> allEntities} — standard multi-entity contract.</li>
 *   <li>PSI directory guard added — prevents {@code dir.add()} collision within the
 *       same {@code WriteCommandAction} when multiple entities are generated.</li>
 *   <li>Added {@code @Version Long version} for optimistic locking — critical in
 *       multi-entity systems where concurrent updates on related entities cause
 *       lost-update anomalies without version checks.</li>
 *   <li>{@code toString()} made {@code protected} so subclass {@code toString()} can
 *       call {@code super.toString()} cleanly.</li>
 * </ul>
 */
public class BaseAuditEntityGenerator {

    public static void generate(
            Project project,
            PsiDirectory root,
            ClassMeta meta,
            List<ClassMeta> allEntities
    ) {
        if (project == null || root == null || meta == null) {
            throw new IllegalArgumentException("Project, root directory, and metadata cannot be null");
        }

        String pkg      = meta.basePackage() + ".entity";
        String fileName = "BaseAuditEntity.java";

        // Disk guard
        if (FileExistsUtil.fileExistsInPackage(root, pkg, fileName)) {
            System.out.println("ℹ️  " + fileName + " already exists on disk — skipping.");
            return;
        }

        PsiDirectory dir = PsiDirectoryUtil.createPackageDirs(root, pkg);

        // PSI directory guard
        if (fileExistsInPsiDirectory(dir, fileName)) {
            System.out.println("ℹ️  " + fileName + " already exists in PSI directory — skipping.");
            return;
        }

        String code = String.format("""
                package %s;
                
                import jakarta.persistence.Column;
                import jakarta.persistence.EntityListeners;
                import jakarta.persistence.MappedSuperclass;
                import jakarta.persistence.Version;
                import org.springframework.data.annotation.CreatedBy;
                import org.springframework.data.annotation.CreatedDate;
                import org.springframework.data.annotation.LastModifiedBy;
                import org.springframework.data.annotation.LastModifiedDate;
                import org.springframework.data.jpa.domain.support.AuditingEntityListener;
                
                import java.time.LocalDateTime;
                
                /**
                 * Base mapped superclass providing automatic audit fields for all entities.
                 *
                 * <p>Subclasses inherit:
                 * <ul>
                 *   <li>{@code createdAt}  — set once on first persist, never updated</li>
                 *   <li>{@code updatedAt}  — updated on every merge</li>
                 *   <li>{@code createdBy}  — principal name at creation time</li>
                 *   <li>{@code updatedBy}  — principal name at last modification</li>
                 *   <li>{@code version}    — optimistic lock counter; prevents lost-update
                 *       anomalies when multiple transactions modify the same or related rows
                 *       concurrently</li>
                 * </ul>
                 *
                 * <p>Requires {@code @EnableJpaAuditing} on a {@code @Configuration} class
                 * (generated by {@code JpaAuditingConfigGenerator}) and a
                 * {@code AuditorAware<String>} bean that returns the current principal name.
                 */
                @MappedSuperclass
                @EntityListeners(AuditingEntityListener.class)
                public abstract class BaseAuditEntity {
                
                    // ── Timestamp audit fields ────────────────────────────────────────
                
                    @CreatedDate
                    @Column(name = "created_at", nullable = false, updatable = false)
                    private LocalDateTime createdAt;
                
                    @LastModifiedDate
                    @Column(name = "updated_at", nullable = false)
                    private LocalDateTime updatedAt;
                
                    // ── Principal audit fields ────────────────────────────────────────
                
                    @CreatedBy
                    @Column(name = "created_by", updatable = false, length = 100)
                    private String createdBy;
                
                    @LastModifiedBy
                    @Column(name = "updated_by", length = 100)
                    private String updatedBy;
                
                    // ── Optimistic locking ────────────────────────────────────────────
                
                    /**
                     * JPA optimistic lock version counter.
                     *
                     * <p>Automatically incremented by the JPA provider on every update.
                     * If two transactions read the same row and both attempt to update it,
                     * the second commit throws {@code OptimisticLockException}, preventing
                     * the lost-update anomaly.
                     *
                     * <p>In multi-entity systems this is especially important when updating
                     * an entity that owns a {@code @ManyToMany} join table — a concurrent
                     * add/remove on the same join table would silently overwrite data
                     * without optimistic locking.
                     */
                    @Version
                    @Column(name = "version", nullable = false)
                    private Long version;
                
                    // ── Getters & Setters ─────────────────────────────────────────────
                
                    public LocalDateTime getCreatedAt() { return createdAt; }
                    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
                
                    public LocalDateTime getUpdatedAt() { return updatedAt; }
                    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
                
                    public String getCreatedBy() { return createdBy; }
                    public void setCreatedBy(String createdBy) { this.createdBy = createdBy; }
                
                    public String getUpdatedBy() { return updatedBy; }
                    public void setUpdatedBy(String updatedBy) { this.updatedBy = updatedBy; }
                
                    public Long getVersion() { return version; }
                
                    /**
                     * Version is managed entirely by the JPA provider — this setter
                     * exists only for framework use (e.g. test fixtures) and must
                     * never be called in application code.
                     */
                    public void setVersion(Long version) { this.version = version; }
                
                    // ── toString ──────────────────────────────────────────────────────
                
                    /**
                     * Returns a string representation of audit fields.
                     *
                     * <p>Declared {@code protected} so subclasses can call
                     * {@code super.toString()} and embed the result in their own
                     * {@code toString()} without re-declaring all audit fields.
                     *
                     * <p>Example in a subclass:
                     * <pre>
                     *   &#64;Override
                     *   public String toString() {
                     *       return "Employee{id=" + id + ", name='" + name + "', " + super.toString() + "}";
                     *   }
                     * </pre>
                     */
                    @Override
                    public String toString() {
                        return "audit={"
                                + "createdAt=" + createdAt
                                + ", updatedAt=" + updatedAt
                                + ", createdBy='" + createdBy + '\\''
                                + ", updatedBy='" + updatedBy + '\\''
                                + ", version=" + version
                                + '}';
                    }
                }
                """, pkg);

        PsiFile file = PsiFileFactory.getInstance(project)
                .createFileFromText(fileName, JavaFileType.INSTANCE, code);

        dir.add(file);
        System.out.println("✅ Generated " + fileName);
    }

    private static boolean fileExistsInPsiDirectory(PsiDirectory dir, String fileName) {
        if (dir == null || fileName == null) return false;
        for (PsiFile existing : dir.getFiles()) {
            if (fileName.equals(existing.getName())) return true;
        }
        return false;
    }
}